/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAB4_20495193_A1.vista;

import LAB4_20495193_A1.controlador.Accept;
import LAB4_20495193_A1.controlador.Login;
import LAB4_20495193_A1.modelo.Respuesta;
import LAB4_20495193_A1.modelo.Stack;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *Frame que se encarga de la eleccion de una respuesta que se quiera aceptar,
 * tiene como atributos al stack, el usuario con sesion iniciada y el id de la
 * pregunta
 * 
 */
public class Faccept extends javax.swing.JFrame {
    private Stack stack;
    private Login usuario;
    private String idPregunta;
    /**
     * Constructor que recibe como parametros el stack, el usuario y el id de
     * la pregunta
     */
    public Faccept(Stack stack, Login usuario,String id) {
        this.stack = stack;
        this.usuario = usuario;
        this.idPregunta = id;
        initComponents();
    }

    private Faccept() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Stack getStack() {
        return stack;
    }

    public void setStack(Stack stack) {
        this.stack = stack;
    }

    public Login getUsuario() {
        return usuario;
    }

    public void setUsuario(Login usuario) {
        this.usuario = usuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTrespuestas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JBback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JTrespuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTrespuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTrespuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTrespuestas);

        jLabel1.setText("Seleccione la respuesta que quiere aceptar:");

        JBback.setText("Volver");
        JBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(JBback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBback)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.elegirRespuesta();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.elegirRespuesta();
    }//GEN-LAST:event_formWindowOpened
    /**
    * Cuando el usuario presione una respuesta entonces el programa ejecutara el proceso
    * de aceptar una respuesta. Para esto se captura el id de la pregunta en un String que
    * se le pasa como parametro a la creacion de una nueva clase Accept, luego se ejecuta el 
    * metodo accept que se encarga de cerra el estado de la pregunta y otorgar la recompensa de
    * esta al usuario autor de la respuesta
    * @param evt 
    */
    private void JTrespuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTrespuestasMouseClicked
        DefaultTableModel tablita = (DefaultTableModel)JTrespuestas.getModel();
        int selectedRowIndex = JTrespuestas.getSelectedRow();
        String auxiliar = (String)JTrespuestas.getValueAt(JTrespuestas.getSelectedRow(), 0);
        Accept aceptar = new Accept(stack,idPregunta,auxiliar);
        aceptar.accept();
        JOptionPane.showMessageDialog(null, "Respuesta aceptada");
        dispose();
    }//GEN-LAST:event_JTrespuestasMouseClicked
     /**
    * Si es que el usuario presiona el boton de volver entonces se cerrara este frame
    * y se volvera al menu de usuario.
    * @param evt 
    */
    private void JBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbackActionPerformed
        dispose();
    }//GEN-LAST:event_JBbackActionPerformed
    //Se muestra por pantalla una tabla con los datos correspondientes a la pregunta
    //para que el usuario pueda elegir una
    private void elegirRespuesta(){ 
        ArrayList<Respuesta> respuestasD = new ArrayList<>();
        respuestasD = stack.buscarRespuestas(stack,idPregunta);
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("ID");
        tablita.addColumn("Autor");
        tablita.addColumn("Contenido");
        tablita.addColumn("Fecha publicacion");
        JTrespuestas.setModel(tablita);
        String[] dato = new String[4];
        for(int i = 0; i < respuestasD.size();i++){
            Respuesta rps = respuestasD.get(i);
            dato[0] = rps.getIdRespuesta()+"";
            dato[1] = rps.getAutor();
            dato[2] = rps.getContenido();
            dato[3] = rps.getFecha();
            tablita.addRow(dato);
        }           
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faccept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faccept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faccept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faccept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faccept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBback;
    private javax.swing.JTable JTrespuestas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
