/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAB4_20495193_A1.vista;

import LAB4_20495193_A1.modelo.Pregunta;
import LAB4_20495193_A1.modelo.Respuesta;
import LAB4_20495193_A1.modelo.Stack;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * Frame que se encarga de mostrar lo que haya encontrado el programa segun el 
 * criterio que escogio el usuario, tiene como atributos al stack, un verificador para
 * saber que tipo de tabla mostrar y 3 arrayList correspondientess a respuestas,preguntas y 
 * etiquetas 
 * 
 */
public class Fbusqueda extends javax.swing.JFrame {
    private Stack stack;
    private int verificador;
    private ArrayList<Respuesta> respuestas;
    private ArrayList<Pregunta> preguntas;
    ArrayList<ArrayList<String>> etiquetas;
    /**
     * Constructor que recibe como parametros un stack, un numero y 3 arraylist
     */
    public Fbusqueda(Stack stack, int verificador, ArrayList<Respuesta> respuestas, ArrayList<Pregunta> preguntas,ArrayList<ArrayList<String>> etiquetas) {
        this.stack = stack;
        this.verificador = verificador;
        this.respuestas = respuestas;
        this.preguntas = preguntas;
        this.etiquetas = etiquetas;
        initComponents();
    }

    private Fbusqueda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Stack getStack() {
        return stack;
    }

    public void setStack(Stack stack) {
        this.stack = stack;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTopciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JBback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JTopciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTopciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTopcionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTopciones);

        jLabel1.setText("Resultado de la busqueda:");

        JBback.setText("Volver");
        JBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(JBback)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBback)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.elegirPregunta();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.elegirPregunta();
    }//GEN-LAST:event_formWindowOpened
    
    private void JTopcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTopcionesMouseClicked
        DefaultTableModel tablita = (DefaultTableModel)JTopciones.getModel();
        int selectedRowIndex = JTopciones.getSelectedRow();
        String auxiliar = (String)JTopciones.getValueAt(JTopciones.getSelectedRow(), 0);
        dispose();
    }//GEN-LAST:event_JTopcionesMouseClicked

    /**
    * Si es que el usuario presiona el boton de volver entonces se cerrara este frame
    * y se volvera al menu de usuario.
    * @param evt 
    */
    private void JBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBbackActionPerformed
   /**
    * Este metodo se encarga de capturar todas las preguntas,etiquetas o respuestas que esten disponibles aun
    * y de mostrar toda su informacion en una tabla que se genera y se le añaden columnas
    * para cada seccion importante del criterio en cuestion. EN el caso de que el verificador fuera un 1
    * entonces se mostrara una tabla para preguntas, si fuera un 2 sera una tabla para respuestas y si fuera
    * un 3 entonces una tabla para etiquetas
    */
    private void elegirPregunta(){
        if(verificador == 1){
            DefaultTableModel tablita = new DefaultTableModel();
            tablita.addColumn("ID");
            tablita.addColumn("Autor");
            tablita.addColumn("Titulo");
            tablita.addColumn("Contenido");
            tablita.addColumn("Etiquetas");
            tablita.addColumn("Fecha publicacion");
            tablita.addColumn("Recompensa");
            JTopciones.setModel(tablita);
            String[] dato = new String[7];
            for(int i = 0; i < preguntas.size();i++){
                Pregunta prg = preguntas.get(i);
                dato[0] = prg.getIdPregunta()+"";
                dato[1] = prg.getAutor();
                dato[2] = prg.getTitulo();
                dato[3] = prg.getContenido();
                dato[4] = prg.getEtiquetas()+"";
                dato[5] = prg.getFechaDePublicacion();
                dato[6] = prg.getRecompensa()+ "";
                tablita.addRow(dato);
            }
        }
        else if(verificador == 2){
            DefaultTableModel tablita = new DefaultTableModel();
            tablita.addColumn("ID");
            tablita.addColumn("Autor");
            tablita.addColumn("Contenido");
            tablita.addColumn("Fecha publicacion");
            JTopciones.setModel(tablita);
            String[] dato = new String[4];
            for(int i = 0; i < respuestas.size();i++){
                Respuesta rps = respuestas.get(i);
                dato[0] = rps.getIdRespuesta()+"";
                dato[1] = rps.getAutor();
                dato[2] = rps.getContenido();
                dato[3] = rps.getFecha();
                tablita.addRow(dato);
            }    
        }
        else if(verificador == 3){
            DefaultTableModel tablita = new DefaultTableModel();
            tablita.addColumn("Nombre etiqueta");
            tablita.addColumn("Descripcion");
            JTopciones.setModel(tablita);
            String[] dato = new String[2];
            for(int i = 0; i < etiquetas.size();i++){
                
                dato[0] = etiquetas.get(i).get(0);
                dato[1] = etiquetas.get(i).get(1);
                tablita.addRow(dato);
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fbusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBback;
    private javax.swing.JTable JTopciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
