/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAB4_20495193_A1.vista;

import LAB4_20495193_A1.controlador.Login;
import LAB4_20495193_A1.modelo.Stack;
import javax.swing.JOptionPane;

/**
 * Frame que se genera si es que algun usuario pudo iniciar sesion,
 * esta clase recibe como atributos al usuario y el stack con el que se
 * esta trabajando
 * @author Admin
 */
public class FmenuUsuario extends javax.swing.JFrame {
    Login usuario;
    Stack stack;
    /**
     * constructor de la clase que recibe como atributos al usuario
     * que inicio sesion y al stack
     */
    public FmenuUsuario(Login usuario,Stack stack) {
        initComponents();
        this.usuario = usuario;
        this.stack = stack;

    }

    private FmenuUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBaddPregunta = new javax.swing.JButton();
        JBanswer = new javax.swing.JButton();
        JBreward = new javax.swing.JButton();
        JBaccept = new javax.swing.JButton();
        JBlogout = new javax.swing.JButton();
        JBexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBaddPregunta.setText("Agregar pregunta");
        JBaddPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBaddPreguntaActionPerformed(evt);
            }
        });

        JBanswer.setText("Responder pregunta");
        JBanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBanswerActionPerformed(evt);
            }
        });

        JBreward.setText("Dar recompensa");
        JBreward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBrewardActionPerformed(evt);
            }
        });

        JBaccept.setText("Aceptar respuesta");
        JBaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBacceptActionPerformed(evt);
            }
        });

        JBlogout.setText("Cerrar Sesión");
        JBlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlogoutActionPerformed(evt);
            }
        });

        JBexit.setText("Salir del programa");
        JBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexitActionPerformed(evt);
            }
        });

        jLabel1.setText("MENU DE USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBanswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBaddPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBreward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBaccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(JBaddPregunta)
                .addGap(18, 18, 18)
                .addComponent(JBanswer)
                .addGap(18, 18, 18)
                .addComponent(JBreward)
                .addGap(18, 18, 18)
                .addComponent(JBaccept)
                .addGap(18, 18, 18)
                .addComponent(JBlogout)
                .addGap(18, 18, 18)
                .addComponent(JBexit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton que esta ligado al cierre de sesion del usuario. si es que
     * el usuario lo presiona entonces se cierra este frame, se le indica por pantalla 
     * al usuario que cerro sesion y se vuelve al menu principal
     * @param evt 
     */
    private void JBlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlogoutActionPerformed
        
        JOptionPane.showMessageDialog(null, "Sesion cerrada");
        dispose();
    }//GEN-LAST:event_JBlogoutActionPerformed
    /**
     * Si el usuario elige salir del programa entonces se paran todos los procesos
     * y se cierra todo 
     * @param evt 
     */
    private void JBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexitActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_JBexitActionPerformed
    /**
     * Boton ligado a la funcionalidad ask para que el usuario pueda añadir una pregunta
     * @param evt 
     */
    private void JBaddPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBaddPreguntaActionPerformed
        
        new Fquestion(stack,usuario).setVisible(true);
    }//GEN-LAST:event_JBaddPreguntaActionPerformed
    /**
     * Boton ligado a la funcionalidad answer para que el usuario pueda añadir una 
     * respuesta a una pregunta que el elija.
     * @param evt 
     */
    private void JBanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBanswerActionPerformed
        new Feleccion(stack,usuario).setVisible(true);
    }//GEN-LAST:event_JBanswerActionPerformed
    /**
     * Boton ligado a la funcionalidad reward para que el usuario pueda premiar 
     * una pregunta que aun este disponible para responder
     * @param evt 
     */
    private void JBrewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBrewardActionPerformed
        new Freward(stack,usuario).setVisible(true);
    }//GEN-LAST:event_JBrewardActionPerformed
    /**
     * Boton ligado a la funcionalidad accept para que el usuario pueda aceptar
     * una respuesta a alguna de las preguntas, si es que es posible.
     * @param evt 
     */
    private void JBacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBacceptActionPerformed
        new Feleccion2(stack,usuario).setVisible(true);
    }//GEN-LAST:event_JBacceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBaccept;
    private javax.swing.JButton JBaddPregunta;
    private javax.swing.JButton JBanswer;
    private javax.swing.JButton JBexit;
    private javax.swing.JButton JBlogout;
    private javax.swing.JButton JBreward;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
