/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAB4_20495193_A1.vista;

import LAB4_20495193_A1.controlador.Login;
import LAB4_20495193_A1.controlador.Reward;
import LAB4_20495193_A1.modelo.Pregunta;
import LAB4_20495193_A1.modelo.Stack;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static javax.swing.JOptionPane.showInputDialog;

/**
 * Frame que se encarga de mostrar al usuario las preguntas disponibles para recompensar
 * y le permite hacer click en la que quiere seleccionar, tiene como atributos a un stack
 * y el usuario que tiene sesion iniciada
 * 
 * 
 */
public class Freward extends javax.swing.JFrame {
    private Stack stack;
    private Login usuario;
    /**
     * constructor de la clase que recibe como parametros un stack y un usuario
     */
    public Freward(Stack stack, Login usuario) {
        this.stack = stack;
        this.usuario = usuario;
        initComponents();
    }

    private Freward() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Stack getStack() {
        return stack;
    }

    public void setStack(Stack stack) {
        this.stack = stack;
    }

    public Login getUsuario() {
        return usuario;
    }

    public void setUsuario(Login usuario) {
        this.usuario = usuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTpreguntas2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JBback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JTpreguntas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTpreguntas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTpreguntas2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTpreguntas2);

        jLabel1.setText("Haga click en la pregunta que desea elegir:");

        JBback.setText("Volver");
        JBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(JBback)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBback)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.elegirPregunta();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.elegirPregunta();
    }//GEN-LAST:event_formWindowOpened
    /**
     * cuando el usuario haga click en una pregunta entonces se capturara el valor del
     * id de la pregunta en un String, entonces se creara una ventana pequeña que le pedira
     * al usuario ingresar el valor de la recompensa a otorgar, luego se genera una clase
     * Reward a la cual se le pasa como parametro el stack,usuario y recompensa, luego se ejecuta
     * el metodo reward donde se le entrega tambien el id de la pregunta. Este metodo indicara si 
     * fue posible o no entregar la recompensa.
     * @param evt 
     */
    private void JTpreguntas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTpreguntas2MouseClicked
        DefaultTableModel tablita = (DefaultTableModel)JTpreguntas2.getModel();
        int selectedRowIndex = JTpreguntas2.getSelectedRow();
        String eleccion = (String)JTpreguntas2.getValueAt(JTpreguntas2.getSelectedRow(), 0);
        String recompensa =  showInputDialog("Introduza la recompensa: ");
        Reward recompensar = new Reward(stack,recompensa,usuario);
        recompensar.reward(stack, usuario, recompensa,eleccion);
        dispose();
    }//GEN-LAST:event_JTpreguntas2MouseClicked
    /**
     * Si es que el usuario presiona el boton de volver entonces se cerrara este frame
     * y se volvera al menu de usuario.
     * @param evt 
     */
    private void JBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbackActionPerformed
        dispose();
    }//GEN-LAST:event_JBbackActionPerformed
    /**
     * Este metodo se encarga de capturar todas las preguntas que esten disponibles aun
     * y de mostrar toda su informacion en una tabla que se genera y se le añaden columnas
     * para cada seccion importante de la pregunta en cuestion.
     */
    private void elegirPregunta(){
        ArrayList<Pregunta> preguntasD;
        preguntasD = stack.mostrarPregunta(stack);
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("ID");
        tablita.addColumn("Autor");
        tablita.addColumn("Titulo");
        tablita.addColumn("Contenido");
        tablita.addColumn("Etiquetas");
        tablita.addColumn("Fecha publicacion");
        tablita.addColumn("Recompensa");
        
        JTpreguntas2.setModel(tablita);
        String[] dato = new String[7];
        for(int i = 0; i < preguntasD.size();i++){
            Pregunta prg = preguntasD.get(i);
            dato[0] = prg.getIdPregunta()+"";
            dato[1] = prg.getAutor();
            dato[2] = prg.getTitulo();
            dato[3] = prg.getContenido();
            dato[4] = prg.getEtiquetas()+"";
            dato[5] = prg.getFechaDePublicacion();
            dato[6] = prg.getRecompensa()+ "";
            tablita.addRow(dato);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Freward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Freward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Freward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Freward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Freward().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBback;
    private javax.swing.JTable JTpreguntas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
